### ISSUE TITLE
Errors on npm run build

### ISSUE THREAD

**Issue by rootscript** [mukeshsoni/frolic#5]
When I run `npm run build`, I get these errors:

```
ERROR in ./app/compilers/react-compiler/index.js
Module not found: Error: Cannot resolve module 'flow-remove-types' in /Users/rootscript/Github/__copy-elm/frolic/app/compilers/react-compiler
 @ ./app/compilers/react-compiler/index.js 31:22-50

ERROR in ./app/compilers/react-compiler/index.js
Module not found: Error: Cannot resolve module 'js-beautify' in /Users/rootscript/Github/__copy-elm/frolic/app/compilers/react-compiler
 @ ./app/compilers/react-compiler/index.js 32:15-37

ERROR in ./app/compilers/react-compiler/index.js
Module not found: Error: Cannot resolve module 'escodegen-wallaby' in /Users/rootscript/Github/__copy-elm/frolic/app/compilers/react-compiler
 @ ./app/compilers/react-compiler/index.js 37:16-44

ERROR in ./app/compilers/react-compiler/webpack.config.js
Module not found: Error: Cannot resolve module 'flow-status-webpack-plugin' in /Users/rootscript/Github/__copy-elm/frolic/app/compilers/react-compiler
 @ ./app/compilers/react-compiler/webpack.config.js 6:30-67
```

If I install these modules manually, then `npm run build` again, then all is good:

```
npm install flow-status-webpack-plugin --save
npm install escodegen-wallaby --save
npm install js-beautify --save
npm install flow-remove-types --save
npm run build
```

btw - THANKS for this tool.

node --version
v6.7.0

elm --version
0.17.1

electron --version
Version 1.4.3

**Comment by rootscript** [comment]
that's quick - thanks again!

**Comment by rootscript** [comment]
I wasn't sure if `devDependencies` or `dependencies` in `package.json`

**Comment by mukeshsoni** [comment]
@rootscript Thanks for reporting. 

The react compiler is not even exposed but is causing the problems. The thing is, i have added a separate package.json for app/compilers/react-compiler, so that i can pull that out into a separate repo in the future. But the thing is not usable right now, so have not exposed it. 

Will probably add an npm script to install dependencies in the react-compiler folder.

**Comment by mukeshsoni** [comment]
Have added a react-compiler script during build. Thanks again @rootscript

**Comment by mukeshsoni** [comment]
@rootscript  Have also fixed a couple other bugs in the latest release. Take the latest and try again.
